[project]
name = "sindri-labs"
version = "0.0.1"
description = "Sindri Python SDK"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/Sindri-Labs/sindri-python"
Issues = "https://github.com/Sindri-Labs/sindri-python/issues"

[tool.black]
line-length = 100
skip-string-normalization = false
target-version = ['py310']
include = '\.pyi?$'
exclude = '''
(
  /(
    | \.git          # root of the project
    | .mypy_cache
    | .pytest_cache
    | __pycache__
  )/
)
'''

[tool.mypy]
python_version = "3.10"
