name: Build & Publish PyPI


# Build and publish to PyPI
# - official PyPI only on tags that start with `v`
# - test PyPI only on tags that start with `test-v`


on:
  release:
    types: [published]

jobs:

  build_and_publish_pypi:
    runs-on: ubuntu-latest
    # Only run this workflow if the tag starts with "v"
    if: startsWith(github.ref, 'refs/tags/v')
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Install poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Update project.toml Version
        run: poetry version $VERSION

      - name: Build and Publish
        env:
            PYPI_TOKEN: ${{ secrets.PYPI_API_TOKEN }}
        run: |
            poetry config pypi-token.pypi $PYPI_TOKEN
            poetry publish --build


  build_and_publish_test_pypi:
    runs-on: ubuntu-latest
    # Only run this workflow if the tag starts with "test-v"
    if: startsWith(github.ref, 'refs/tags/test-v')
    needs: [lint]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set Up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Extract Version from Tag
        run: echo "VERSION=${GITHUB_REF#refs/tags/test-v}" >> $GITHUB_ENV

      - name: Install poetry
        run: pip install poetry

      - name: Install Dependencies
        run: poetry install

      - name: Update project.toml Version
        run: poetry version $VERSION

      - name: Build and Publish
        env:
            TEST_PYPI_TOKEN: ${{ secrets.TEST_PYPI_API_TOKEN }}
        run: |
            poetry config pypi-token.test-pypi $TEST_PYPI_TOKEN
            poetry config repositories.test-pypi https://test.pypi.org/legacy/
            poetry publish --build --repository test-pypi
